### ISSUE TITLE
Can't get the sample app to run

### ISSUE THREAD

**Issue by bjorndaniel** [anthonychu/AzureAdvocates.WebJobs.Extensions.SignalRService#1]
I cloned the repo and tried running the function but it starts and ends immediately, see attached image.
I have tried following the instructions in the read me with the same result.
Is there something that I am missing?

![image](https://user-images.githubusercontent.com/802037/40307901-86740500-5d04-11e8-88f2-ceeccc0eb762.png)

**Comment by anthonychu** [comment]
You need to have a SignalR Service instance created and the connection string in a setting called `AzureSignalRConnectionString`.

You also need the extension installed. I believe you can do this by running `func extensions sync`. Otherwise, just follow the instructions in the README and run the `func extensions install ...` command.

**Comment by anthonychu** [comment]
You also need to start a web server to serve the index.html file in /content.

You will run into CORS errors, you need to start the function host with CORS enabled.

**Comment by bjorndaniel** [comment]
Closing this issue as it was an issue unrelated to this repo. For anyone else seeing this, the issue was that I had node 9 installed. Once I downgraded to 8.11.2 it worked like a charm!
